import type { ToolcraftComponentAcceptance, ToolcraftExportRequestEvidence } from "./acceptance/types";
import { ISO_TARGETS } from "./iso/iso-state";

const specs = {
  motion: "e2e/product-iso-motion.spec.ts",
} as const;

/**
 * The user accepted the offered export option for the animated relief. The
 * answer is kept verbatim; the video interpretation is recorded in the worklog.
 */
export const videoExportRequestEvidence: ToolcraftExportRequestEvidence = {
  messageRef: "ask-user-question:relief-wave-animation:export",
  messageText:
    '"Что должно попадать в экспорт при включённой анимации?"="PNG + видео (Recommended)"',
  quote: "PNG + видео",
  source: "user-message",
};

/** Acceptance rows for the looping relief wave, its timeline, and video delivery. */
export const appMotionAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "presets apply complete grid and wave setups",
    browser: {
      budget: "standard",
      file: specs.motion,
      testName: "browser acceptance: a saved preset restores its settings and layout",
    },
    componentType: "custom",
    evidence: "rendered-pixels",
    expectedObservable:
      "Each preset name is a full-width button that reshapes the grid and the relief in one undoable step; local builds also rename, overwrite and reorder them.",
    fixture: "default flat field",
    id: "presets.saved",
    interactionId: "saved-presets",
    kind: "control",
    target: ISO_TARGETS.savedPresets,
    userAction: "Click each preset name, then Undo.",
  },
  {
    automated: true,
    automatedTestName: "wave turns the relief into a looping travelling wave",
    browser: {
      budget: "standard",
      file: specs.motion,
      testName: "browser acceptance: wave switch animates the relief on the timeline",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "With Wave on, the columns rise and fall smoothly as the timeline plays; off, the relief is static.",
    fixture: "corner pattern with the timeline playing",
    id: "relief.wave",
    kind: "control",
    target: ISO_TARGETS.reliefWave,
    userAction: "Toggle Wave and scrub the timeline.",
  },
  {
    automated: true,
    automatedTestName: "wave length spaces the crests",
    browser: {
      budget: "standard",
      file: specs.motion,
      testName: "browser acceptance: wave length changes the crest spacing while dragging",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Wave length moves the crests further apart or closer together at the same timeline time.",
    fixture: "corner wave paused mid-loop",
    id: "relief.waveLength",
    kind: "control",
    target: ISO_TARGETS.reliefWaveLength,
    userAction: "Pause the timeline and drag Wave length.",
  },
  {
    automated: true,
    automatedTestName: "wave direction sends crests from or to the peak",
    browser: {
      budget: "standard",
      file: specs.motion,
      testName: "browser acceptance: wave direction reverses where the crests travel",
    },
    componentType: "segmented",
    evidence: "rendered-pixels",
    expectedObservable: "From peak moves the crests away from the peak corner; To peak moves them towards it.",
    fixture: "corner wave paused mid-loop",
    id: "relief.waveDirection",
    kind: "control",
    optionCoverage: ["outward", "inward"],
    target: ISO_TARGETS.reliefWaveDirection,
    userAction: "Select each direction and scrub the timeline.",
  },
  {
    automated: true,
    automatedTestName: "wave easing shapes how columns rise and fall",
    browser: {
      budget: "standard",
      file: specs.motion,
      testName: "browser acceptance: wave easing changes the column motion",
    },
    componentType: "select",
    evidence: "rendered-pixels",
    expectedObservable: "Each easing gives the same crest positions but different column heights on the way up and down.",
    fixture: "corner wave paused mid-loop",
    id: "relief.waveEasing",
    kind: "control",
    optionCoverage: ["sine", "linear", "ease-in", "ease-out", "ease-in-out"],
    target: ISO_TARGETS.reliefWaveEasing,
    userAction: "Pause the timeline, pick each easing, and compare the column outlines.",
  },
  {
    automated: true,
    automatedTestName: "relief wave loops seamlessly on the timeline",
    browser: {
      budget: "standard",
      file: specs.motion,
      testName: "browser acceptance: relief wave plays, pauses, scrubs, and loops",
    },
    componentType: "timeline",
    evidence: "timeline-output",
    expectedObservable:
      "Playing moves the wave forward, pausing freezes it, scrubbing shows the matching frame, and the last frame joins the first after a duration edit.",
    fixture: "corner wave",
    id: "timeline.relief-wave",
    kind: "runtime",
    target: "timeline.playback",
    timelineCoverage: "playback",
    timelineLoopProof: {
      direction: "forward-only",
      durationChange: "reproved-after-edit",
      reversePlayback: "forbidden",
      seam: "first-last-match",
    },
    timelinePlaybackCoverage: "all-playback-behavior",
    userAction: "Play, pause, scrub, and change the loop duration.",
  },
  {
    automated: true,
    automatedTestName: "video formats remain selectable",
    browser: {
      budget: "extended-io",
      file: specs.motion,
      testName: "browser acceptance: video formats export MP4 and WebM",
    },
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "MP4 and WebM each export a decodable video of the wave loop.",
    fixture: "corner wave",
    id: "export.video.format",
    kind: "control",
    optionCoverage: ["mp4", "webm"],
    target: "export.video.format",
    userAction: "Select each video format and export.",
  },
  {
    automated: true,
    automatedTestName: "video resolutions remain selectable",
    browser: {
      budget: "extended-io",
      file: specs.motion,
      testName: "browser acceptance: video resolutions set the exported size",
    },
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Current keeps the artboard size and 4K fits the set inside 3840×2160.",
    fixture: "corner wave",
    id: "export.video.resolution",
    kind: "control",
    optionCoverage: ["current", "4k"],
    target: "export.video.resolution",
    userAction: "Select each video resolution and export.",
  },
  {
    actionCoverage: ["export.png", "export.video"],
    automated: true,
    automatedTestName: "video export renders the wave loop",
    browser: {
      budget: "extended-io",
      file: specs.motion,
      testName: "browser acceptance: Export video downloads the looping wave",
    },
    componentType: "panelActions",
    evidence: "exported-bytes",
    exportArtifactCoverage: "all-required-video-export-behavior",
    expectedObservable: "The downloaded video lasts one loop at 30 FPS and its frames show the wave moving.",
    fixture: "corner wave with placed rolls",
    id: "export.video",
    kind: "control",
    target: "actions.output",
    userAction: "Click Export video and inspect the decoded download.",
  },
  {
    automated: true,
    automatedTestName: "infinity video export keeps one frame for the whole loop",
    browser: {
      budget: "extended-io",
      file: specs.motion,
      testName: "browser acceptance: Infinity video export keeps the set frame still",
    },
    componentType: "canvas",
    evidence: "exported-bytes",
    expectedObservable: "Infinity video export uses one frame that fits the wave at its highest and lowest.",
    fixture: "corner wave in Infinity mode",
    id: "canvas.infinity-video-export",
    infinityCanvasCoverage: "scene-bounds-video-export",
    kind: "runtime",
    target: "canvas.infinity",
    userAction: "Enable Infinity canvas, export video, and compare every frame size.",
  },
];
