import type {
  ToolcraftComponentAcceptance,
  ToolcraftProductReadiness,
  ToolcraftTransferMode,
} from "./acceptance/types";
import { appMotionAcceptance, videoExportRequestEvidence } from "./app-acceptance-motion";
import { appReliefAcceptance } from "./app-acceptance-relief";
import { appInteractionOwnership, canvasPlacementCommand } from "./app-interaction-ownership";
import { appSchema } from "./app-schema";
import {
  ISO_ACTIONS,
  ISO_FIELD_HANDLE_TEST_ID,
  ISO_TARGETS,
} from "./iso/iso-state";
export { appControlSectionInventory } from "./app-control-inventory";

const persistenceSlices =
  appSchema.persistence.storage === "localStorage"
    ? appSchema.persistence.include
    : [];

const objectLibraryFitCheck = {
  capabilities: ["selection", "custom-interaction", "custom-value-model"],
  checkedBuiltIns: [
    "fileDrop",
    "sourceCollection",
    "collectionActions",
    "imagePicker",
    "vector",
    "segmented",
    "slider",
    "text",
  ],
  closestBuiltIn: "fileDrop",
  productObservable:
    "Changing the active object's anchor, footprint, or scale moves or resizes only that object's pieces on the canvas and in the exported PNG.",
  whyInsufficient:
    "The FileDrop collection variant accepts one file per slot and removes only the last slot, sourceCollection edits a single field per item, imagePicker has no per-item settings, and Vector cannot set the anchor by clicking an enlarged preview of the uploaded image as requested.",
} as const satisfies NonNullable<ToolcraftComponentAcceptance["builtInFitCheck"]>;

const specs = {
  field: "e2e/product-iso-field.spec.ts",
  grid: "e2e/product-iso-grid.spec.ts",
  library: "e2e/product-iso-library.spec.ts",
  output: "e2e/product-iso-output.spec.ts",
} as const;

export const appTransferMode: ToolcraftTransferMode = {
  animationIntent: {
    loopDuration: {
      evidence:
        "One loop moves the wave by exactly one crest; four seconds keeps the default six-cell wave calm and readable at card size.",
      seconds: 4,
      source: "product-derived",
    },
    mode: "timeline-playback",
  },
  mode: "new-toolcraft-app",
  referenceInputs: [],
};

export const appProductReadiness: ToolcraftProductReadiness = {
  exportIntent: {
    image: { mode: "toolcraft-default" },
    svg: { mode: "not-requested" },
    video: { evidence: videoExportRequestEvidence, mode: "user-requested" },
  },
  interactionOwnership: appInteractionOwnership,
  mode: "product",
  productName: "Iso Sushi Set Builder",
  productSummary:
    "Builds isometric sushi set compositions from transparent PNG rolls placed on a dashed vector isometric grid.",
  requestedBehavior:
    "Upload roll PNGs, configure footprint, anchor, and scale per object, place, fill, select, and erase pieces on a 2×2 to 8×8 rhombus grid, raise columns by hand with magnetic snapping or from relief patterns, loop the relief as a smooth travelling wave on the timeline, preview the set at app card widths, and export a cropped transparent PNG.",
  viewInteraction: {
    mode: "non-spatial",
    reason:
      "Flat roll sprites are laid out in a fixed isometric projection; there is no three-dimensional model or camera to rotate.",
  },
};

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "declares production reload coverage for the generated product schema",
    browser: {
      budget: "extended-io",
      file: "e2e/app-persistence.spec.ts",
      testName: "browser: app restores exact canvas, values, and panel workspace slices after reload",
    },
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "Canvas size and zoom, their runtime values, and the moved and collapsed Controls workspace remain visibly restored after a real browser reload.",
    fixture: "sushi set persisted workspace",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices,
    target: "canvas.size.width",
    userAction: "Edit Canvas width and zoom, move and collapse Controls, wait for persistence, and reload the page.",
  },
  {
    automated: true,
    automatedTestName: "background inclusion keeps the set foreground transparent",
    backgroundOutputCoverage: [
      "finite-media-stacking",
      "image-transparent-when-excluded",
      "infinity-viewport-color-and-dependency",
      "video-background-preserved",
      "preview-hidden-when-excluded",
    ],
    browser: {
      budget: "standard",
      file: specs.output,
      testName: "browser acceptance: background inclusion controls preview and PNG transparency",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "Background off removes the artboard fill and exports transparent corners; Background on paints the colour and enables Infinity canvas.",
    fixture: "placed set with Background toggled",
    id: "background.include",
    kind: "control",
    target: ISO_TARGETS.includeBackground,
    userAction: "Toggle Background and compare preview, Infinity availability, and PNG alpha.",
  },
  {
    automated: true,
    automatedTestName: "background colour is painted behind the exported set",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: background colour reaches the exported PNG",
    },
    componentType: "color",
    evidence: "exported-bytes",
    expectedObservable: "The selected Background color appears in the exported PNG corners.",
    fixture: "placed set with Background on",
    id: "background.color",
    kind: "control",
    target: ISO_TARGETS.background,
    userAction: "Turn Background on, change Background color, and inspect decoded export corners.",
  },
  {
    automated: true,
    automatedTestName: "grid size rebuilds the rhombus field from 2 to 8 cells",
    browser: {
      budget: "standard",
      file: specs.grid,
      testName: "browser acceptance: grid size slider rebuilds the field",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable:
      "Dragging Size redraws the dashed field with 2 to 8 cells per side while the pointer is held.",
    fixture: "empty field",
    id: "grid.size",
    kind: "control",
    target: ISO_TARGETS.gridSize,
    userAction: "Drag the discrete Size slider and compare the rendered field.",
  },
  {
    automated: true,
    automatedTestName: "cell size scales the projected field",
    browser: {
      budget: "standard",
      file: specs.grid,
      testName: "browser acceptance: cell size resizes the field live",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Cell resizes the rendered field during the drag.",
    fixture: "empty field",
    id: "grid.cellSize",
    interactionId: "grid-cell-size",
    kind: "control",
    target: ISO_TARGETS.cellSize,
    userAction: "Drag the Cell slider thumb and watch the field size.",
  },
  {
    automated: true,
    automatedTestName: "grid visibility toggles the dashed lines",
    browser: {
      budget: "standard",
      file: specs.grid,
      testName: "browser acceptance: grid visibility hides and shows the dashed field",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Turning Visible off removes the dashed grid lines from the canvas.",
    fixture: "empty field",
    id: "grid.visible",
    kind: "control",
    target: ISO_TARGETS.gridVisible,
    userAction: "Toggle Visible and compare the canvas.",
  },
  {
    automated: true,
    automatedTestName: "library uploads become objects and removal clears their pieces",
    browser: {
      budget: "extended-io",
      file: specs.library,
      testName: "browser acceptance: library uploads, reorders, removes, and resets object images",
    },
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable:
      "Uploaded PNGs appear as objects that can be placed; removing one clears its pieces; Reset removes uploads.",
    fixture: "two generated transparent PNG rolls",
    id: "library.files",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "remove", "reorder", "order-output", "reset"],
    target: ISO_TARGETS.libraryFiles,
    userAction: "Upload two PNGs, reorder them, place one, remove it, and reset.",
  },
  {
    automated: true,
    automatedTestName: "object settings change only the selected object's pieces",
    browser: {
      budget: "standard",
      file: specs.library,
      testName: "browser acceptance: object anchor, footprint, and scale edit only the selected object",
    },
    builtInFitCheck: objectLibraryFitCheck,
    componentType: "isoObjectLibrary",
    customControlCoverage: "all-custom-control-behavior",
    evidence: "rendered-pixels",
    expectedObservable:
      "Selecting an object and editing its anchor, footprint, or scale changes only that object's pieces on the canvas.",
    fixture: "two objects placed side by side",
    id: "library.objects",
    interactionId: "object-properties",
    kind: "control",
    selectionScopeCoverage: "two-entity-isolation",
    target: ISO_TARGETS.libraryObjects,
    userAction: "Select object A, click its preview to move the anchor and change scale; then select object B and edit it.",
  },
  {
    automated: true,
    automatedTestName: "active object selection decides which object is placed",
    browser: {
      budget: "standard",
      file: specs.library,
      testName: "browser acceptance: selecting an object makes it the one placed on the field",
    },
    builtInFitCheck: objectLibraryFitCheck,
    componentType: "isoObjectLibrary",
    customControlCoverage: "all-custom-control-behavior",
    evidence: "rendered-pixels",
    expectedObservable: "After choosing another object in the library, a cell click places that object instead.",
    fixture: "two uploaded objects with different colours",
    id: "library.active-object",
    interactionId: "object-select",
    kind: "control",
    target: ISO_TARGETS.libraryObjects,
    userAction: "Choose the second object's thumbnail, then click an empty cell with Place.",
  },
  {
    automated: true,
    automatedTestName: "tool mode decides what a cell click does",
    browser: {
      budget: "standard",
      file: specs.field,
      testName: "browser acceptance: tool mode switches between place, select, erase, and height",
    },
    componentType: "segmented",
    evidence: "rendered-pixels",
    expectedObservable:
      "The same cell click places a piece with Place, selects with Select, removes it with Erase, and a vertical drag raises the column with Height.",
    fixture: "one uploaded object",
    id: "field.tool",
    kind: "control",
    optionCoverage: ["place", "select", "erase", "height"],
    target: ISO_TARGETS.tool,
    userAction: "Click or drag a cell with each tool and compare the canvas.",
  },
  {
    actionCoverage: [ISO_ACTIONS.fillSelection, ISO_ACTIONS.fillField, ISO_ACTIONS.clearField],
    automated: true,
    automatedTestName: "field commands fill a section, fill the field, and clear it",
    browser: {
      budget: "standard",
      file: specs.field,
      testName: "browser acceptance: field commands fill a section, fill the field, and clear it",
    },
    componentType: "actions",
    evidence: "rendered-pixels",
    expectedObservable: "Fill section tiles the selection, Fill field tiles every cell, and Clear field empties the canvas.",
    fixture: "one uploaded 2×1 object with a selected section",
    id: "field.commands",
    interactionId: "field-commands",
    kind: "control",
    target: ISO_TARGETS.commands,
    userAction: "Select a section, click Fill section, Fill field, and Clear field.",
  },
  {
    automated: true,
    automatedTestName: "composition summary counts pieces per object",
    browser: {
      budget: "standard",
      file: specs.field,
      testName: "browser acceptance: composition shows counts, total, and card previews",
    },
    builtInFitCheck: {
      capabilities: ["custom-visualization"],
      checkedBuiltIns: ["sourceCollection", "collectionActions", "imagePicker"],
      closestBuiltIn: "none",
      productObservable:
        "Placing or erasing pieces on the field updates the per-object counts, the total, and the card-width previews.",
      whyInsufficient:
        "No built-in control shows live per-object piece counts with a total or renders the composition at 170 and 340 px app card widths; these are read-only summaries of canvas-owned placements.",
    },
    componentType: "isoComposition",
    customControlCoverage: "all-custom-control-behavior",
    evidence: "product-output",
    expectedObservable: "Counts, total, and the card preview update after pieces are placed.",
    fixture: "two objects with pieces on the field",
    id: "field.composition",
    kind: "control",
    target: ISO_TARGETS.placements,
    userAction: "Place pieces of two objects and read the composition summary and card previews.",
  },
  {
    automated: true,
    automatedTestName: "place tool fills only valid footprints",
    browser: {
      budget: "standard",
      file: specs.field,
      testName: "browser acceptance: place tool puts the active object on a clicked cell",
    },
    canvasHandle: {
      outputObservable: "A roll appears on the clicked cell; an overlapping or out-of-grid click adds nothing.",
      testId: ISO_FIELD_HANDLE_TEST_ID,
      writesTarget: canvasPlacementCommand,
    },
    componentType: "canvas-handle",
    evidence: "rendered-pixels",
    expectedObservable: "A piece renders on the clicked cell and the hover highlight turns red for blocked cells.",
    fixture: "one uploaded 2×2 object",
    id: "field.place",
    interactionId: "field-place",
    kind: "canvas-handle",
    target: canvasPlacementCommand,
    userAction: "Click an empty cell, then hover and click an occupied cell.",
  },
  {
    automated: true,
    automatedTestName: "section selection normalizes a dragged cell rectangle",
    browser: {
      budget: "standard",
      file: specs.field,
      testName: "browser acceptance: select tool drags a section that Fill section tiles",
    },
    canvasHandle: {
      outputObservable: "The dragged section fills with pieces after Fill section.",
      testId: ISO_FIELD_HANDLE_TEST_ID,
      writesTarget: canvasPlacementCommand,
    },
    componentType: "canvas-handle",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging over cells outlines a section and Fill section fills exactly that section.",
    fixture: "one uploaded object",
    id: "field.select",
    interactionId: "field-select",
    kind: "canvas-handle",
    target: canvasPlacementCommand,
    userAction: "Drag across cells with Select, then click Fill section.",
  },
  {
    automated: true,
    automatedTestName: "eraser removes a clicked object or the selected section",
    browser: {
      budget: "standard",
      file: specs.field,
      testName: "browser acceptance: erase tool removes a clicked object and a selected section",
    },
    canvasHandle: {
      outputObservable: "The clicked piece or every piece in the selected section disappears.",
      testId: ISO_FIELD_HANDLE_TEST_ID,
      writesTarget: canvasPlacementCommand,
    },
    componentType: "canvas-handle",
    evidence: "rendered-pixels",
    expectedObservable: "Erasing removes the clicked piece, then the selected section's pieces.",
    fixture: "filled field with a selected section",
    id: "field.erase",
    interactionId: "field-erase",
    kind: "canvas-handle",
    target: canvasPlacementCommand,
    userAction: "Click a piece with Erase, then click inside the selected section.",
  },
  ...appReliefAcceptance,
  ...appMotionAcceptance,
  {
    automated: true,
    automatedTestName: "crop modes frame the field or the content",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: crop mode frames the exported PNG",
    },
    componentType: "segmented",
    evidence: "exported-bytes",
    expectedObservable: "Off exports the manual artboard, Field fits the field, and Content fits only the pieces.",
    fixture: "partially filled field",
    id: "output.crop",
    kind: "control",
    optionCoverage: ["off", "field", "content"],
    target: ISO_TARGETS.crop,
    userAction: "Select each Crop mode and export PNG.",
  },
  {
    automated: true,
    automatedTestName: "crop padding grows the frame on every side",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: crop padding grows the exported PNG",
    },
    componentType: "slider",
    evidence: "exported-bytes",
    expectedObservable: "Increasing Padding enlarges the artboard and the exported PNG around the set.",
    fixture: "content crop of placed pieces",
    id: "output.padding",
    kind: "control",
    target: ISO_TARGETS.padding,
    userAction: "Drag Padding and export PNG.",
  },
  {
    automated: true,
    automatedTestName: "show rolls hides every piece from the preview and export",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: show rolls off exports only the grid",
    },
    componentType: "switch",
    evidence: "exported-bytes",
    expectedObservable:
      "Turning Show rolls off removes every roll from the canvas and card previews, and the PNG with Grid in export contains only the dashed grid.",
    fixture: "placed set with Grid in export on",
    id: "output.showPieces",
    kind: "control",
    target: ISO_TARGETS.showPieces,
    userAction: "Turn Show rolls off, export PNG, and inspect the decoded download.",
  },
  {
    automated: true,
    automatedTestName: "grid can be included in the export",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: grid in export adds dashed lines to the PNG",
    },
    componentType: "switch",
    evidence: "exported-bytes",
    expectedObservable: "The exported PNG has no grid by default and shows the dashed grid when Grid in export is on.",
    fixture: "placed set with visible grid",
    id: "output.includeGrid",
    kind: "control",
    target: ISO_TARGETS.includeGrid,
    userAction: "Export PNG with Grid in export off and on.",
  },
  {
    automated: true,
    automatedTestName: "image format options remain selectable",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: image formats export PNG and JPG",
    },
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "PNG and JPG downloads decode with their selected format.",
    fixture: "placed set",
    id: "export.image.format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Select PNG and JPG and export.",
  },
  {
    automated: true,
    automatedTestName: "image resolution options remain selectable",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: image resolutions set the exported long edge",
    },
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "2K, 4K, and 8K exports have 2048, 4096, and 8192 px long edges.",
    fixture: "placed set",
    id: "export.image.resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Select each resolution and export.",
  },
  {
    actionCoverage: ["export.png", "export.video"],
    automated: true,
    automatedTestName: "image export renders the placed set",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: Export PNG downloads the composed set",
    },
    componentType: "panelActions",
    evidence: "exported-bytes",
    exportArtifactCoverage: "all-required-image-export-behavior",
    expectedObservable: "The downloaded PNG contains the placed rolls, raised with their columns, at the selected size.",
    fixture: "placed set",
    id: "export.image",
    kind: "control",
    target: "actions.output",
    userAction: "Click Export PNG and inspect the decoded download.",
  },
  {
    automated: true,
    automatedTestName: "sushi set scene bounds stay centred on the origin",
    browser: {
      budget: "standard",
      file: specs.output,
      testName: "browser acceptance: Infinity canvas keeps the set frame continuous",
    },
    componentType: "canvas",
    evidence: "viewport-side-effect",
    expectedObservable:
      "Infinity mode removes only the finite boundary while the set, its frame, and the view stay continuous; turning it off restores the artboard.",
    fixture: "placed set with Background on",
    id: "canvas.infinity",
    infinityCanvasCoverage: "mode-continuity-and-restoration",
    kind: "runtime",
    target: "canvas.infinity",
    userAction: "Toggle Infinity canvas on and off.",
  },
  {
    automated: true,
    automatedTestName: "infinity export crops to the set frame",
    browser: {
      budget: "extended-io",
      file: specs.output,
      testName: "browser acceptance: Infinity export crops to the set frame",
    },
    componentType: "canvas",
    evidence: "exported-bytes",
    expectedObservable: "Infinity PNG export crops to the set frame instead of the dormant artboard size.",
    fixture: "placed set in Infinity mode",
    id: "canvas.infinity-export",
    infinityCanvasCoverage: "scene-bounds-image-export",
    kind: "runtime",
    target: "canvas.infinity",
    userAction: "Enable Infinity canvas, export PNG, and compare decoded size with the set frame.",
  },
];
