import type { ToolcraftComponentAcceptance } from "./acceptance/types";
import { canvasPlacementCommand } from "./app-interaction-ownership";
import { ISO_FIELD_HANDLE_TEST_ID, ISO_RELIEF_ACTIONS, ISO_TARGETS } from "./iso/iso-state";

const specs = {
  grid: "e2e/product-iso-grid.spec.ts",
  relief: "e2e/product-iso-relief.spec.ts",
} as const;

/** Acceptance rows for column heights: the Height tool, relief patterns, and level height. */
export const appReliefAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "relief patterns raise columns live",
    browser: {
      budget: "standard",
      file: specs.relief,
      testName: "browser acceptance: relief pattern dropdown reshapes the columns live",
    },
    componentType: "select",
    evidence: "rendered-pixels",
    expectedObservable: "Each pattern immediately raises a different set of columns; Flat lowers them to the ground.",
    fixture: "empty field",
    id: "relief.pattern",
    kind: "control",
    optionCoverage: [
      "flat",
      "corner-diagonal",
      "corner-rings",
      "edge",
      "pyramid",
      "checker",
      "alternate-rows",
      "alternate-cols",
    ],
    target: ISO_TARGETS.reliefPattern,
    userAction: "Pick each pattern and compare the column outlines.",
  },
  {
    automated: true,
    automatedTestName: "relief peak corner moves the highest column",
    browser: {
      budget: "standard",
      file: specs.relief,
      testName: "browser acceptance: relief peak moves the highest column live",
    },
    componentType: "segmented",
    evidence: "rendered-pixels",
    expectedObservable: "The highest column moves to the chosen field corner as soon as it is picked.",
    fixture: "corner pattern",
    id: "relief.corner",
    kind: "control",
    optionCoverage: ["top", "right", "bottom", "left"],
    target: ISO_TARGETS.reliefCorner,
    userAction: "Pick each peak corner and compare the column outlines.",
  },
  {
    automated: true,
    automatedTestName: "relief edge picks the slope side",
    browser: {
      budget: "standard",
      file: specs.relief,
      testName: "browser acceptance: relief side moves the slope live",
    },
    componentType: "segmented",
    evidence: "rendered-pixels",
    expectedObservable: "The raised columns move to the chosen field side as soon as it is picked.",
    fixture: "edge pattern",
    id: "relief.edge",
    kind: "control",
    optionCoverage: ["top-left", "top-right", "bottom-right", "bottom-left"],
    target: ISO_TARGETS.reliefEdge,
    userAction: "Pick each side and compare the column outlines.",
  },
  {
    automated: true,
    automatedTestName: "relief peak height scales applied levels",
    browser: {
      budget: "standard",
      file: specs.relief,
      testName: "browser acceptance: peak height resizes the relief while dragging",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Peak height raises or lowers the relief during the drag.",
    fixture: "corner pattern",
    id: "relief.max",
    kind: "control",
    target: ISO_TARGETS.reliefMax,
    userAction: "Drag Peak height and watch the column outlines.",
  },
  {
    automated: true,
    automatedTestName: "relief falloff widens each level band",
    browser: {
      budget: "standard",
      file: specs.relief,
      testName: "browser acceptance: falloff widens the relief bands while dragging",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Falloff widens or narrows each level band during the drag.",
    fixture: "corner pattern",
    id: "relief.step",
    kind: "control",
    target: ISO_TARGETS.reliefStep,
    userAction: "Drag Falloff and watch the column outlines.",
  },
  {
    automated: true,
    automatedTestName: "level height scales raised columns live",
    browser: {
      budget: "standard",
      file: specs.grid,
      testName: "browser acceptance: level height stretches raised columns live",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Level makes raised columns taller or shorter during the drag.",
    fixture: "field with raised columns",
    id: "grid.levelHeight",
    kind: "control",
    target: ISO_TARGETS.levelHeight,
    userAction: "Drag the Level slider and watch the raised columns.",
  },
];
